// +build !ignore_autogenerated

/*
+Copyright 2018 The Kubernetes Authors.
+
+Licensed under the Apache License, Version 2.0 (the "License");
+you may not use this file except in compliance with the License.
+You may obtain a copy of the License at
+
+    http://www.apache.org/licenses/LICENSE-2.0
+
+Unless required by applicable law or agreed to in writing, software
+distributed under the License is distributed on an "AS IS" BASIS,
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	federation "github.com/irfanurrehman/federationV2/pkg/apis/federation"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Deployment_To_federation_Deployment,
		Convert_federation_Deployment_To_v1alpha1_Deployment,
		Convert_v1alpha1_DeploymentList_To_federation_DeploymentList,
		Convert_federation_DeploymentList_To_v1alpha1_DeploymentList,
		Convert_v1alpha1_DeploymentSpec_To_federation_DeploymentSpec,
		Convert_federation_DeploymentSpec_To_v1alpha1_DeploymentSpec,
		Convert_v1alpha1_DeploymentStatus_To_federation_DeploymentStatus,
		Convert_federation_DeploymentStatus_To_v1alpha1_DeploymentStatus,
		Convert_v1alpha1_DeploymentStatusStrategy_To_federation_DeploymentStatusStrategy,
		Convert_federation_DeploymentStatusStrategy_To_v1alpha1_DeploymentStatusStrategy,
		Convert_v1alpha1_DeploymentStrategy_To_federation_DeploymentStrategy,
		Convert_federation_DeploymentStrategy_To_v1alpha1_DeploymentStrategy,
	)
}

func autoConvert_v1alpha1_Deployment_To_federation_Deployment(in *Deployment, out *federation.Deployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DeploymentSpec_To_federation_DeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeploymentStatus_To_federation_DeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Deployment_To_federation_Deployment is an autogenerated conversion function.
func Convert_v1alpha1_Deployment_To_federation_Deployment(in *Deployment, out *federation.Deployment, s conversion.Scope) error {
	return autoConvert_v1alpha1_Deployment_To_federation_Deployment(in, out, s)
}

func autoConvert_federation_Deployment_To_v1alpha1_Deployment(in *federation.Deployment, out *Deployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_federation_DeploymentSpec_To_v1alpha1_DeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_federation_DeploymentStatus_To_v1alpha1_DeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_federation_Deployment_To_v1alpha1_Deployment is an autogenerated conversion function.
func Convert_federation_Deployment_To_v1alpha1_Deployment(in *federation.Deployment, out *Deployment, s conversion.Scope) error {
	return autoConvert_federation_Deployment_To_v1alpha1_Deployment(in, out, s)
}

func autoConvert_v1alpha1_DeploymentList_To_federation_DeploymentList(in *DeploymentList, out *federation.DeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]federation.Deployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_DeploymentList_To_federation_DeploymentList is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentList_To_federation_DeploymentList(in *DeploymentList, out *federation.DeploymentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentList_To_federation_DeploymentList(in, out, s)
}

func autoConvert_federation_DeploymentList_To_v1alpha1_DeploymentList(in *federation.DeploymentList, out *DeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Deployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_federation_DeploymentList_To_v1alpha1_DeploymentList is an autogenerated conversion function.
func Convert_federation_DeploymentList_To_v1alpha1_DeploymentList(in *federation.DeploymentList, out *DeploymentList, s conversion.Scope) error {
	return autoConvert_federation_DeploymentList_To_v1alpha1_DeploymentList(in, out, s)
}

func autoConvert_v1alpha1_DeploymentSpec_To_federation_DeploymentSpec(in *DeploymentSpec, out *federation.DeploymentSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_DeploymentSpec_To_federation_DeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentSpec_To_federation_DeploymentSpec(in *DeploymentSpec, out *federation.DeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentSpec_To_federation_DeploymentSpec(in, out, s)
}

func autoConvert_federation_DeploymentSpec_To_v1alpha1_DeploymentSpec(in *federation.DeploymentSpec, out *DeploymentSpec, s conversion.Scope) error {
	return nil
}

// Convert_federation_DeploymentSpec_To_v1alpha1_DeploymentSpec is an autogenerated conversion function.
func Convert_federation_DeploymentSpec_To_v1alpha1_DeploymentSpec(in *federation.DeploymentSpec, out *DeploymentSpec, s conversion.Scope) error {
	return autoConvert_federation_DeploymentSpec_To_v1alpha1_DeploymentSpec(in, out, s)
}

func autoConvert_v1alpha1_DeploymentStatus_To_federation_DeploymentStatus(in *DeploymentStatus, out *federation.DeploymentStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_DeploymentStatus_To_federation_DeploymentStatus is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentStatus_To_federation_DeploymentStatus(in *DeploymentStatus, out *federation.DeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentStatus_To_federation_DeploymentStatus(in, out, s)
}

func autoConvert_federation_DeploymentStatus_To_v1alpha1_DeploymentStatus(in *federation.DeploymentStatus, out *DeploymentStatus, s conversion.Scope) error {
	return nil
}

// Convert_federation_DeploymentStatus_To_v1alpha1_DeploymentStatus is an autogenerated conversion function.
func Convert_federation_DeploymentStatus_To_v1alpha1_DeploymentStatus(in *federation.DeploymentStatus, out *DeploymentStatus, s conversion.Scope) error {
	return autoConvert_federation_DeploymentStatus_To_v1alpha1_DeploymentStatus(in, out, s)
}

func autoConvert_v1alpha1_DeploymentStatusStrategy_To_federation_DeploymentStatusStrategy(in *DeploymentStatusStrategy, out *federation.DeploymentStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_DeploymentStatusStrategy_To_federation_DeploymentStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentStatusStrategy_To_federation_DeploymentStatusStrategy(in *DeploymentStatusStrategy, out *federation.DeploymentStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentStatusStrategy_To_federation_DeploymentStatusStrategy(in, out, s)
}

func autoConvert_federation_DeploymentStatusStrategy_To_v1alpha1_DeploymentStatusStrategy(in *federation.DeploymentStatusStrategy, out *DeploymentStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_federation_DeploymentStatusStrategy_To_v1alpha1_DeploymentStatusStrategy is an autogenerated conversion function.
func Convert_federation_DeploymentStatusStrategy_To_v1alpha1_DeploymentStatusStrategy(in *federation.DeploymentStatusStrategy, out *DeploymentStatusStrategy, s conversion.Scope) error {
	return autoConvert_federation_DeploymentStatusStrategy_To_v1alpha1_DeploymentStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_DeploymentStrategy_To_federation_DeploymentStrategy(in *DeploymentStrategy, out *federation.DeploymentStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_DeploymentStrategy_To_federation_DeploymentStrategy is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentStrategy_To_federation_DeploymentStrategy(in *DeploymentStrategy, out *federation.DeploymentStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentStrategy_To_federation_DeploymentStrategy(in, out, s)
}

func autoConvert_federation_DeploymentStrategy_To_v1alpha1_DeploymentStrategy(in *federation.DeploymentStrategy, out *DeploymentStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_federation_DeploymentStrategy_To_v1alpha1_DeploymentStrategy is an autogenerated conversion function.
func Convert_federation_DeploymentStrategy_To_v1alpha1_DeploymentStrategy(in *federation.DeploymentStrategy, out *DeploymentStrategy, s conversion.Scope) error {
	return autoConvert_federation_DeploymentStrategy_To_v1alpha1_DeploymentStrategy(in, out, s)
}
